.gitignore
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
추가 했습니다.
=> [refactor] gitignore 파일 수정

pull_request_template.md
PR 템플릿 설정했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
=> [chore] PR 템플릿 설정

android/app/build.gradle, lib/main.dart, lib/screens/auth/signup_screen.dart, pubspec.lock, pubspec.yaml
=> [Feat] 회원가입 기능 추가

lib/main.dart, lib/routes/app_router.dart, lib/routes/auth_routes.dart, lib/routes/community_routes.dart, lib/routes/main_routes.dart, lib/routes/onboarding_routes.dart, lib/routes/plants_routes.dart, lib/routes/profile_routes.dart, lib/screens/auth/login_screen.dart, lib/screens/auth/login_start_screen.dart, lib/screens/auth/signup_screen.dart, lib/screens/community/post_create_screen.dart, lib/screens/community/post_detail_screen.dart, lib/screens/main/main_screen.dart, lib/screens/modals/comment_modal.dart, lib/screens/modals/timeline_modal.dart, lib/screens/notifications/push_notifications_screen.dart, lib/screens/onboarding/plant_onboarding_screen.dart, lib/screens/plants/my_plant_collection_screen.dart, lib/screens/plants/my_plant_timeline_screen.dart, lib/screens/profile/my_page_edit_screen.dart, lib/screens/profile/my_page_screen.dart, lib/screens/search/search_screen.dart, lib/widgets/components/bottom_navigation_bar.dart, lib/widgets/components/comment_item.dart, lib/widgets/components/memo_item.dart, lib/widgets/components/post_item.dart, lib/widgets/profile/change_password_modal.dart, pubspec.lock, pubspec.yaml
flutter analyze fix를 완료 했습니다.
_submitForm은 곧 사용될 기능이라 제거하지 않았습니다.
=> [fix] flutter analyze fix 완료

lib/screens/plants/my_plant_register_screen.dart
=> _submitForm 주석 처리 완료

lib/screens/auth/login_screen.dart
firebase연동으로 로그인 기능을 구현하였습니다.
경고문구를 추가하였습니다
=> [feat] 로그인 기능 구현

lib/screens/auth/login_screen.dart, lib/screens/auth/signup_screen.dart
로그인, 회원가입 성공시 토스터 메세지가 나오도록 추가했습니다.
회원가입 오류 메세지 스낵바를 제거했습니다.
=> [Feat] 로그인, 회원가입 페이지 기능 추가

lib/routes/app_router.dart, lib/screens/community/post_detail_screen.dart, lib/screens/modals/memo_create_modal.dart, lib/screens/modals/notification_setting_modal.dart, lib/screens/plants/my_plant_timeline_screen.dart, lib/widgets/inputs/emoji_selector.dart, lib/widgets/profile/change_password_modal.dart
- 내식물타임라인페이지 UI 수정 (LIKE, D-DAY, 물주기알림)
- 메모작성 모달창 UI 수정
- 알림설정 모달창 UI 수정
- PW변경 모달창 UI 수정
*하트이모티콘은 크롬에서는 핑크로 잘 나오는데 avd에서는 빨간색으로 나오네요,,
=> [design] 내식물타임라인페이지 퍼블리싱

lib/widgets/components/post_item.dart
=> [fix] 게시물 오류 해결

lib/screens/community/all_posts_screen.dart, lib/screens/community/post_create_screen.dart, lib/screens/community/post_detail_screen.dart, lib/widgets/components/post_item.dart
게시물(전체, 상세) 페이지 정보 없음 부분 오류 해결했습니다.
데이터 저장 이슈로 인해 환경 부분(일조량, 물 주는 양, 온도)은 구현하지 않았습니다.
=> [fix] 게시물(전체, 상세) 페이지 정보 없음 부분 오류 해결

lib/screens/community/all_posts_screen.dart, lib/screens/community/post_create_screen.dart, lib/widgets/components/post_item.dart
=> [fix] 사용자 닉네임, 프로필 보이기

lib/screens/main/main_screen.dart, lib/screens/profile/my_page_edit_screen.dart, lib/screens/profile/my_page_screen.dart
=> 게시글과 firebase 연동 기능 구현

lib/screens/modals/comment_modal.dart, lib/widgets/components/comment_item.dart
- 댓글에 닉네임을 추가했습니다.
- SnackBar를 Fluttertoast로 변경했습니다.
- Navigator를 goRouter로 변경했습니다.
=> [refactor] 댓글에 닉네임 추가

lib/screens/main/main_screen.dart
=> [Refactor] 메인페이지 오류 해결

lib/screens/main/main_screen.dart, lib/widgets/components/post_item.dart
=> [refactor] ui 깨짐 수정 완료

lib/screens/community/post_create_screen.dart, lib/screens/community/post_detail_screen.dart, lib/screens/main/main_screen.dart, lib/screens/profile/my_page_edit_screen.dart, lib/screens/profile/my_page_screen.dart, lib/widgets/components/post_item.dart
마이페이지 게시물에 이미지를 올리지 않을 경우 게시물 처리가 되지 않는 문제를 해결 했습니다
기본 프로필 이미지가 뜨지 않던걸 수정했습니다.
=> [fix] 마이페이지 게시물 목록 오류 해결

lib/screens/search/search_screen.dart, pubspec.lock
최근 검색어 기능 구현 완료했습니다.
최근 검색어가 시간순으로 아래에 뜨고 클릭하면 해당 검색 페이지로 넘어갑니다. 
전체 삭제 버튼으로 검색어를 삭제할 수 있습니다.
=> 최근검색어 기능 완료

lib/routes/map_routes.dart, lib/screens/map/map_create_screen.dart, lib/screens/map/map_screen.dart
- 지도페이지에 추가버튼을 생성했습니다.
- 지도식물등록페이지를 퍼블리싱했습니다.
=> [design] 지도식물등록페이지 퍼블리싱

ios/Podfile.lock, ios/Runner/Info.plist, lib/routes/map_routes.dart, lib/screens/map/map_create_screen.dart, lib/screens/map/map_screen.dart, lib/screens/modals/location_modal.dart, lib/util/addressAndLatLng.dart, pubspec.lock, pubspec.yaml
- 현재위치 불러오기
- 위치 직접 설정하기
- firebase에 데이터 저장하기
=> [feat] 지도 식물 등록페이지 구현

lib/screens/community/post_create_screen.dart, lib/screens/community/post_detail_screen.dart, lib/screens/main/main_screen.dart, lib/widgets/components/post_item.dart
- 전체게시물페이지 뒤로가기 버튼 추가
- 작성 날짜 반영
- 좋아요 상태 관리
- 전체게시물페이지 UI 정렬
- 이미지 안 올린 경우 상세페이지에서도 이미지 안보이게
=> [fix] 게시물 관련 오류 수정

android/app/src/main/AndroidManifest.xml, pubspec.lock
AndroidManifest.xml 오류 해결했습니다.
=> [fix] AndroidManifest.xml 오류 해결
